// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: pb/event.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EventStreamer_StreamEvents_FullMethodName = "/pb.EventStreamer/StreamEvents"
)

// EventStreamerClient is the client API for EventStreamer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EventStreamerClient interface {
	// client-streaming RPC: producer sends a continuous stream of batches
	// over a single connection and receives one acknowledgement when the
	// stream is closed.
	StreamEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[EventBatch, EventAck], error)
}

type eventStreamerClient struct {
	cc grpc.ClientConnInterface
}

func NewEventStreamerClient(cc grpc.ClientConnInterface) EventStreamerClient {
	return &eventStreamerClient{cc}
}

func (c *eventStreamerClient) StreamEvents(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[EventBatch, EventAck], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &EventStreamer_ServiceDesc.Streams[0], EventStreamer_StreamEvents_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[EventBatch, EventAck]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventStreamer_StreamEventsClient = grpc.ClientStreamingClient[EventBatch, EventAck]

// EventStreamerServer is the server API for EventStreamer service.
// All implementations must embed UnimplementedEventStreamerServer
// for forward compatibility.
type EventStreamerServer interface {
	// client-streaming RPC: producer sends a continuous stream of batches
	// over a single connection and receives one acknowledgement when the
	// stream is closed.
	StreamEvents(grpc.ClientStreamingServer[EventBatch, EventAck]) error
	mustEmbedUnimplementedEventStreamerServer()
}

// UnimplementedEventStreamerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEventStreamerServer struct{}

func (UnimplementedEventStreamerServer) StreamEvents(grpc.ClientStreamingServer[EventBatch, EventAck]) error {
	return status.Error(codes.Unimplemented, "method StreamEvents not implemented")
}
func (UnimplementedEventStreamerServer) mustEmbedUnimplementedEventStreamerServer() {}
func (UnimplementedEventStreamerServer) testEmbeddedByValue()                       {}

// UnsafeEventStreamerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EventStreamerServer will
// result in compilation errors.
type UnsafeEventStreamerServer interface {
	mustEmbedUnimplementedEventStreamerServer()
}

func RegisterEventStreamerServer(s grpc.ServiceRegistrar, srv EventStreamerServer) {
	// If the following call panics, it indicates UnimplementedEventStreamerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EventStreamer_ServiceDesc, srv)
}

func _EventStreamer_StreamEvents_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(EventStreamerServer).StreamEvents(&grpc.GenericServerStream[EventBatch, EventAck]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type EventStreamer_StreamEventsServer = grpc.ClientStreamingServer[EventBatch, EventAck]

// EventStreamer_ServiceDesc is the grpc.ServiceDesc for EventStreamer service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EventStreamer_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.EventStreamer",
	HandlerType: (*EventStreamerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamEvents",
			Handler:       _EventStreamer_StreamEvents_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "pb/event.proto",
}
